// ============================================================
// SINGLE SOURCE OF TRUTH — update here, everything else syncs
// ============================================================
// This file is generated by LaunchFolio from your resume + enrichment.
// After download, edit only this file — the site, README, and PDF
// resume all render from it automatically via CI/CD.
// ============================================================
const resumeData = {

  name:      "",
  title:     "",
  tagline1:  "",
  tagline2:  "",
  sub:       "",
  location:  "",
  email:     "",
  linkedin:  "",
  github:    "",
  portfolio: "",
  credly:    "",
  phone:      "",
  twitter:    "",
  leetcode:   "",
  hackerrank: "",

  heroBadges: [],

  summary: "",

  focus: [],

  skills: [],

  experience: [],

  certifications: [],

  projects: [],

  education: [],

  achievements: [],

  // extras: custom additional sections — any title, any items
  // type: "list" (bullet points) | "tags" (chips) — defaults to "list"
  // Examples: Accomplishments, Awards, Soft Skills, Languages, Publications
  extras: []
};
